### ISSUE TITLE
Move to ddev org

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-solr#17]
This repo is ready to move to the [ddev org](github.com/ddev). 

When you're ready to move it @mkalkbrenner let me know and I'll give you permissions on github.com/ddevl and you can transfer it there, and then I'll transfer it to ddev.

Related: 
* https://github.com/ddev/ddev/issues/5002

**Comment by mkalkbrenner** [comment]
Thanks! We should do so after finishing the configset upload test in #13

**Comment by rfay** [comment]
I have invited you to the ddevl org as owner; you can move this there and I'll move it from there to the ddev org.

**Comment by rfay** [comment]
Hoping we can do this soon, all you have to do is transfer it, then I'll transfer it, then it needs a PR to change naming instances.

**Comment by rfay** [comment]
@mkalkbrenner you can just do the transfer any time. Looks like you accepted the invite OK, so you can just transfer to the ddevl org and I'll immediately transfer to ddev org.

**Comment by mkalkbrenner** [comment]
@rfay I have a question before doing the move. I just finished Solr 9 support for Drupal.
It works with ddev by just changing this line:
https://github.com/mkalkbrenner/ddev-solr/blob/ffe1c06c050d8ab46d98da94341822d80c8e445b/docker-compose.solr.yaml#L5

How do we deal with that in official add-ons? Do we need to provide different ones? One for Solr 8 and one for Solr 9? Or should we document to change docker-compose.solr.yaml?

**Comment by mkalkbrenner** [comment]
I moved the project

**Comment by rfay** [comment]
Yay, it's moved. Now please fix it up to change the references to the project, and then do a new release.

**Comment by rfay** [comment]
And then we have to deprecate ddev-drupal9-solr and clear things up in its docs.

**Comment by gitressa** [comment]
The new add-on works perfectly, thanks @mkalkbrenner and @rfay! I made a PR (#25) to update the install path to use `ddev/ddev-solr` and the test path as well.

I hope https://github.com/ddev/ddev-drupal9-solr/ won't be removed, since many still use it?

**Comment by rfay** [comment]
Thanks, closing this. Thanks for the PR @gitressa - is there other cleanup to be done @mkalkbrenner ?

@gitressa can you suggest a good future for ddev-drupal9-solr? I could move it to my user (github redirects work great). We could just put a big USE ddev-solr IF YOU CAN at the top of its readme? If you have a suggestion, please PR it, thanks!
