### ISSUE TITLE
Solr version 9

### ISSUE THREAD

**Issue by nassaz** [ddev/ddev-solr#26]
Is it possible to add Solr version 9? Could you please explain how the Solr release cycles update are planned in ddev?

**Comment by rfay** [comment]
You can experiment and contribute. 

Try a `docker-compose.solr_extra.yaml` with:

```
services:
  solr:
    image: solr:9
```

and see what happens.

**Comment by mkalkbrenner** [comment]
https://github.com/ddev/ddev-solr/pull/32
