### ISSUE TITLE
 Access Solr admin over HTTPS in DDEV by default

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev-solr#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In Firefox, you need to disable [HTTPS-Only Mode in Firefox](https://support.mozilla.org/en-US/kb/https-only-prefs) to access Solr, since it's using HTTP, which is not ideal.

### Describe your solution

It would be great with Solr access over HTTPS as the default, if it's possible.

### Additional context

Kevin Quillen's blog post [Access Apache Solr admin over HTTPS in DDEV](https://kevinquillen.com/access-apache-solr-admin-over-https-ddev).

**Comment by mkalkbrenner** [comment]
```
environment:
      # This defines the host name the service should be accessible from. This
      # will be solr.sitename.ddev.site.
      - VIRTUAL_HOST=solr.$DDEV_HOSTNAME
      # HTTP_EXPOSE exposes http traffic from the container port 8983
      # to the host port 8983 vid ddev-router reverse proxy.
      - HTTP_EXPOSE=8983:8983
      - HTTPS_EXPOSE=443:8983
```

OK, this isn't true HTTPS between the router and Solr. But it makes sense as simple workaround for Firefox and also your app uses CSP headers to redirect to HTTPS.

**Comment by mkalkbrenner** [comment]
I'll add this after the Solr 9 support is committed.

**Comment by rfay** [comment]
The HTTPS_EXPOSE has been problematic in the past because the Solr admin did an odd redirect on some/many browsers. Hopefully that's fixed. But that's why it was removed in previous revisions.

**Comment by mkalkbrenner** [comment]
Using port 443 might cause conflicts with the application if it server `/solr` as well.

**Comment by mkalkbrenner** [comment]
If I add `HTTPS_EXPOSE=8943:8983, ddev status gives me `https://dummy.ddev.site:8943`.
This gets redirected to `http://dummy.ddev.site:8943/solr`, which doesn't work (http instead of https).
If I enter `https://dummy.ddev.site:8943/solr` manually, it works.

@rfay is there any way to append `/solr` to the URL shown by ddev status?

**Comment by rfay** [comment]
Great troubleshooting. 

DDEV doesn't have a way to know what the default URI should be (it auto-discovers the port). But you might consider a `solr` custom command added by the add-on. Then people could do `ddev solr`, or `ddev solradmin`. Just a knock-off on all the many other custom commands that do a launch, like `ddev phpmyadmin`. https://github.com/ddev/ddev-phpmyadmin/blob/main/commands/host/phpmyadmin

Related:
* https://github.com/ddev/ddev/issues/5469

**Comment by rfay** [comment]
@kevinquillen article on a solution, https://kevinquillen.com/access-apache-solr-admin-over-https-ddev

@kevinquillen if this can be done reliably, how about a PR?

**Comment by mkalkbrenner** [comment]
@rfay as mentioned above in https://github.com/ddev/ddev-solr/issues/27#issuecomment-2090293344 this works, but the link in `ddev status` breaks.

**Comment by kevinquillen** [comment]
@mkalkbrenner @rfay that would be fixed with this change in a future release, right? The output will reflect the host and port overrides. I haven't quite had an issue with https redirect otherwise.

https://github.com/ddev/ddev/pull/6136

**Comment by stasadev** [comment]
I got to the root of the problem:

- #27

**Comment by stasadev** [comment]
@mkalkbrenner
This won't work https://github.com/ddev/ddev-solr/commit/0398b27eeafb58729a8bddf8a9d547553c249860
HTTPS support is only for the UI, meaning you still need to access it via HTTP inside the container.

**Comment by kevinquillen** [comment]
I think so, somewhat. This fixes the https redirect, the other shows customization. The PR I made last month will make the `ddev describe` reflect all cases correctly.

**Comment by gitressa** [comment]
Thanks everyone! It's so great to be able to access Solr over HTTPS.

**Comment by gitressa** [comment]
I created a follow-up issue #41.
