### ISSUE TITLE
SOlR's collection is not persistent post ddev restart

### ISSUE THREAD

**Issue by SamitKhulve-materialplus** [ddev/ddev-solr#29]
Facing following 2 issues.

1. Solr collection is not creating automatically, i have to create it manually by following [this doc](https://solr.apache.org/guide/8_7/collection-management.html)
2. Solr collection is not persistent post ddev restart. post restart we have to create the collection and upload the cojfigset again and again by using following comand.
`ddev drush --numShards=1 search-api-solr:upload-configset SEARCH_API_SERVER_ID`

Please let me know how to resolve above issues.

Thanks
Samit K.

**Comment by mkalkbrenner** [comment]
you should not create the collection "manually". the drush command will also create the collection. And it is persistent.

**Comment by SamitKhulve-materialplus** [comment]
Hi @mkalkbrenner ,

getting following error.


$ ddev drush --numShards=1 search-api-solr:upload-configset local_solr

In StandardSolrCloudConnector.php line 264:
                                                                                                                                                             
  Configset upload failed with error code 28: Solr HTTP error: HTTP request failed, Operation timed out after 30000 milliseconds with 0 bytes received (28)  
                                                                                                                                                             
In Curl.php line 60:
                                                                                                                 
  Solr HTTP error: HTTP request failed, Operation timed out after 30000 milliseconds with 0 bytes received (28)  
                                                                                                                 
Failed to run drush --numShards=1 search-api-solr:upload-configset local_solr: exit status 28

**Comment by SamitKhulve-materialplus** [comment]
Closing this issue, I missed to update the host from localhost to solr.

Thanks
Samit K.
