### ISSUE TITLE
Config reset on every restart?

### ISSUE THREAD

**Issue by ChristianAdamski** [ddev/ddev-solr#35]
Simple observation with ddev & Search API Solr.

Everytime I restart it says on /admin/config/search/search-api/server/[my-server]:

> Error message
> You are using an incompatible Solr schema. Please follow the instructions described in the [README.md](http://drupal.ddev.site/modules/contrib/search_api_solr/README.md) file for setting up Solr.

Then I do:

>  ddev drush solr-upload-conf [my-server]

and its fine. Until restarting ddev.

Any ideas? Did nothing to the config files at .ddev/solr directory, all pretty fresh install.

**Comment by mkalkbrenner** [comment]
That's strange. Meanwhile 0.4.0 has been tested by different people with and without search_api_solr.
What is the name of the collection?

**Comment by mkalkbrenner** [comment]
Maybe you should delete the solr docker volume once.
Is there still a zookeeper container running? It should be gone with 0.4.0

**Comment by ChristianAdamski** [comment]
![grafik](https://github.com/ddev/ddev-solr/assets/8464825/cb1dfab2-2acc-47ae-bf05-31188442fe11)

![grafik](https://github.com/ddev/ddev-solr/assets/8464825/91a0021a-3c7e-4a40-8aeb-53e412a86080)

After restart / before uploading config
![grafik](https://github.com/ddev/ddev-solr/assets/8464825/054786b5-a9ad-460f-a504-76498a286d17)

**Comment by ChristianAdamski** [comment]
After uploading config (via drush)

![grafik](https://github.com/ddev/ddev-solr/assets/8464825/df32a212-bd7a-4440-b74d-da7ded981edd)

**Comment by ChristianAdamski** [comment]
There is no data loss. And the drush command is simple enough, so this not particular cumbersome. It was just highly frustrating until I figured out what's happening.

**Comment by mkalkbrenner** [comment]
techproducts is the example collection included in the Solr distribution and gets resettet to its own schema on every start. You must create your own collection in drupal, using a different name, not `techproducts`.

The techproducts example uses a totally different schema which is not a drupal-compatible schema.

BTW We were of the opinion that having this example collection is better than nothing. I just removed the example to avoid confusion: https://github.com/ddev/ddev-solr/pull/36

**Comment by ChristianAdamski** [comment]
First, thanks for the response. I now remove "techproducts" collection and instead added my own "geotest". I'm the maintainer of "geolocation" module on d.o and tested Spatial stuff. This is relevant because:

The spatial context JTS was not working before, it was after the change, also allowing for indexing of polygons. Thats good.

However: after "ddev restart", collection "techproducts" reappeared and my collection "geotest" is completly broken and test data unavailable,

**Comment by mkalkbrenner** [comment]
delete the solr docker volume or run ddev delete

**Comment by ChristianAdamski** [comment]
Started from scratch, removed images, container, volumes. Created a new collection in the solr admin. Connected in search api and tried to upload new configset. Also tried with drush. Browser & drush says "Success", but no change.

See image:
![grafik](https://github.com/ddev/ddev-solr/assets/8464825/bd925d8c-4b65-4a99-b822-66d6750458bc)

**Comment by mkalkbrenner** [comment]
I can't believe that this should be fresh installation.
Previously you used the techproducts configset, now you use the _default configset which is built-in in Solr. Both have nothing to do with drupal.
Drupal should create a configset using the name of the search_api server.

**Comment by mkalkbrenner** [comment]
OK, if the collection already exists, "upload configset" re-uses the name of the configset.
You should not create the collection manually!
Delete all collections and let drupal create it. (like described in Search API Solr's README.)

**Comment by ChristianAdamski** [comment]
Ok, I let Search API create the collection, that worked, and it now also "survives" a restart.

So, my mistakes:

1.) Going by the README.MD "Default Solr collection: techproducts" I used that, and it was constantly reseting.
2.) Going by the Server "collection" field description, I created my "own" collection:
> The name that identifies the Solr default collection to use. The concrete collection to use could be overwritten per index. The most common use-case is to leverage this default collection. Only sophisticated multi-site setups or foreign indexes accessed via Solr Document Datasources or specific requirements of your Solr hosting provider might require to leave this field empty. Because of that, the field is not marked as required as it should be for most use-cases.

**Comment by ChristianAdamski** [comment]
So, this can be closed. Thanks!

Separately I am struggling with WKT / JTS, but that would be a separate issue.
