### ISSUE TITLE
Tests are failing against stable (but not HEAD)

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-solr#38]
[tests](https://github.com/ddev/ddev-solr/actions) are failing against stable. I don't know why they're not failing against HEAD.

Please fix, thanks @mkalkbrenner !

**Comment by rfay** [comment]
I'm not sure, but this could be related to https://github.com/ddev/github-action-add-on-test/pull/31

**Comment by julienloizelet** [comment]
Hi there,
I can see that the permission are not the right one to use the v2:
https://github.com/ddev/ddev-solr/blob/main/.github/workflows/tests.yml#L24

It should be `actions:write` .

Thanks

**Comment by mkalkbrenner** [comment]
The tests started to fail 2 days ago without any change to ddev-solr. In fact, the tests themselves don't fail.

@rfay As the yaml file is derived from the template, is there a fix?

**Comment by julienloizelet** [comment]
For the past  [2 days](https://github.com/ddev/github-action-add-on-test/releases/tag/v2.0.1), the test action is trying to keep alive the repo on every run (using this [ keepalive action](https://github.com/gautamkrishnar/keepalive-workflow/)).

But the keepalive action needs `actions:write` permissions.

(Template has been modified: https://github.com/ddev/ddev-addon-template/blob/main/.github/workflows/tests.yml#L24)

**Comment by rfay** [comment]
Yay, fixed, thanks! https://github.com/ddev/ddev-solr/actions
