### ISSUE TITLE
Multisite search - Collection connection keeps fluctuating

### ISSUE THREAD

**Issue by wilfi** [ddev/ddev-solr#42]
I’m performing a multisite search per this guide here - https://www.drupal.org/docs/8/modules/search-api-solr/search-api-solr-howtos/set-up-and-configure-a-multisite-search

With ddev-solr add-on, I connected Site A SOLR endpoint to Site B. Server status shows as - 'The Solr server could be reached.'

When I point the specific collection of Site A SOLR to Site B, it initially showed as ' The collection could be accessed' , but when I keep refreshing the page it shows as 'The Solr collection could not be accessed. Further data is therefore unavailable.'

This is not consistent as well. It keeps fluctuating. 

And I'm facing the same problem when I do any search with the cloned multisite index from Site A on Site B. At times the result shows 0 , at times it errors out, at times it gives the right resultset. 

Is this expected behaviour? Or am I doing something wrong.

Thankyou.

**Comment by wilfi** [comment]
![Uploading Screenshot 2024-06-27 at 3.10.08 AM.png…]()

**Comment by wilfi** [comment]
<img width="1970" alt="Screenshot 2024-06-27 at 3 15 10 AM" src="https://github.com/ddev/ddev-solr/assets/6604995/f13bcac3-80c9-48ed-8c33-f7b174ca1a89">

**Comment by rfay** [comment]
If you show the configuration for the first site and the second site, and make it clear which one has the solr service, maybe we'll have something to say.

**Comment by wilfi** [comment]
Sure. Let me detail it out here.

- Site A has ddev-solr installed and Site B don't have it installed
- Site B wants to read Site A through Site A's cloned Multisite index (Index name - Multisite Solr Live Index 3u11yw)
- Multisite Solr Live Index 3u11yw is creaed with default settings with Solr multisite document datasource
- The multisite server index is exported from Site A and imported to Site B. It got imported successfully.
- Site B has all the solr cache disabled

<img width="1869" alt="Screenshot 2024-06-27 at 2 41 54 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/d5ca1cac-f88d-4db9-8b42-5ff82e6ac203">


**Current behaviour**
- Site B is able to connect to Site A server. Shows - The solr server could be reached
- Site B shows solr collection could not be accessed. When reloading the page this error goes away and its intermittend. It keeps coming back when i refresh the page.
- When creating a view or implementing a custom search query in Site B using the multisite index of Site A, the result is not consistent. (Assume its due to the above problem?)

Attaching the Site A & B's Search server configs and Site A's multisite index yaml (which is imported to Site B)

[multisearch_index.yml.txt](https://github.com/user-attachments/files/16011325/multisearch_index.yml.txt)
[site_a_search_server.yml.txt](https://github.com/user-attachments/files/16011326/site_a_search_server.yml.txt)
[site_b_search_server.yml.txt](https://github.com/user-attachments/files/16011327/site_b_search_server.yml.txt)

**Comment by wilfi** [comment]
https://github.com/ddev/ddev-solr/assets/6604995/8995ab9b-765c-4f31-995f-23fec8ff9410

Here is the video clip of what I'm experiencing. This is from Site B.

**Comment by mkalkbrenner** [comment]
The `host` in site_b_search_server.txt is wrong. `solr` would access the ddev-solr service of site B, which doesn't exist.
The host name has to be something like `site-b.ddev.site`.

**Comment by mkalkbrenner** [comment]
@rfay Even if the config isn't correct, I don't understand how site B, which is a different ddev project, could sometimes reach the solr service of site A. With that configuration (the wrong host name) it should never reach it. Is there a general issue with the router?

**Comment by rfay** [comment]
@mkalkbrenner Projects can connect to each others' services using their fully-qualified container names, like `ddev-projecta-solr` or `ddev-projectb-db`, etc. 

@wilfi unfortunately I can't read your configurations, and github says the images are not available to zoom in on. If you could please just show the configuration pages of each as a screenshot.

**Comment by wilfi** [comment]
> The `host` in site_b_search_server.txt is wrong. `solr` would access the ddev-solr service of site B, which doesn't exist. The host name has to be something like `site-b.ddev.site`.

This is what I tried initially, but wasn't working until I switched to `solr`

**Comment by wilfi** [comment]
> @mkalkbrenner Projects can connect to each others' services using their fully-qualified container names, like `ddev-projecta-solr` or `ddev-projectb-db`, etc.
> 
> @wilfi unfortunately I can't read your configurations, and github says the images are not available to zoom in on. If you could please just show the configuration pages of each as a screenshot.

@rfay 
Here we go - I assume you want to see the server configuration page. Let me know if you want the edit page as well.

**Site B (No solr)**


<img width="2026" alt="Screenshot 2024-06-27 at 7 26 47 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/65488a78-b87b-48ce-b028-55edc1816382">


Site A
<img width="1589" alt="Screenshot 2024-06-27 at 7 26 04 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/e522bc48-b52c-45b5-89e7-37c4b48130f4">

**Comment by wilfi** [comment]
Here is the edit page screenshots just in case if you want to see.

**Site B**

<img width="2020" alt="Screenshot 2024-06-27 at 7 18 50 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/532a9f0c-8698-49a3-8817-a0398fe6e898">
<img width="1989" alt="Screenshot 2024-06-27 at 7 19 06 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/01dd325f-2511-4d7d-a99e-6eae04038658">
<img width="2008" alt="Screenshot 2024-06-27 at 7 19 20 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/08d74ad1-483c-424d-9f21-5cb22a305cac">
<img width="1979" alt="Screenshot 2024-06-27 at 7 19 29 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/a1503129-3c22-4dd4-bc4a-bcdd445271f0">



**Site A**


<img width="1725" alt="Screenshot 2024-06-27 at 7 30 38 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/e3706d96-6345-4229-ae43-362091ad5e31">
<img width="1968" alt="Screenshot 2024-06-27 at 7 31 03 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/30d40b2d-7580-4537-be89-9be3b9b76fd8">
<img width="1990" alt="Screenshot 2024-06-27 at 7 31 23 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/7c6275b9-8921-4d6f-86a0-b4be02ac4ba2">
<img width="2005" alt="Screenshot 2024-06-27 at 7 31 39 PM" src="https://github.com/ddev/ddev-solr/assets/6604995/df487736-e025-4ebd-ad21-7be81df0438f">

**Comment by wilfi** [comment]
I think I got the problem. The hostname / node should be like `ddev-<projectname>-solr`. 

> The `host` in site_b_search_server.txt is wrong. `solr` would access the ddev-solr service of site B, which doesn't exist. The host name has to be something like `site-b.ddev.site`.


This from @mkalkbrenner made me realise to try with the solr image name. In fact the message thread from @rfay  from #ddev slack channel also conveys the same. 

Turns out to be a simpler one than I thought. Thankyou both for the amazing work :) 

I'll wait for both your go-ahead to close this one out, unless we want to talk about this


> @rfay Even if the config isn't correct, I don't understand how site B, which is a different ddev project, could sometimes reach the solr service of site A. With that configuration (the wrong host name) it should never reach it. Is there a general issue with the router?

**Comment by rfay** [comment]
Glad you got it going!

**Comment by rfay** [comment]
@mkalkbrenner I should have answered your question:

> With that configuration (the wrong host name) it should never reach it. Is there a general issue with the router?

With this configuration, the router is not in play at all, it's direct point-to-point between each `ddev-webserver` and the appropriate `ddev-<projectname>-solr`

@wilfi I'm glad you've got it going. None of your posts seems to show a correct configuration though. Please explain the final result so that if somebody wants to do this in the future they can figure it out

AFAICT the "solr node" should be named `ddev-site1-solr` or whatever on both Drupal instances.

**Comment by wilfi** [comment]
So here is the final working configuration.

**Site B**
<img width="1075" alt="Screenshot 2024-06-28 at 12 18 02 AM" src="https://github.com/ddev/ddev-solr/assets/6604995/2462cda7-4769-40d2-acda-bcf471203e8c">

Key point - Make sure hostname / node points to -  `ddev-<projectname>-solr` (Site A Solr image name)

**Comment by rfay** [comment]
Thanks!
