### ISSUE TITLE
You are using an incompatible Solr schema. Please follow the instructions described in the README.md file for setting up Solr.

### ISSUE THREAD

**Issue by prashantdsala** [ddev/ddev-solr#43]
With latest search api module getting this error:

`You are using an incompatible Solr schema. Please follow the instructions described in the README.md file for setting up Solr.`

and related issue for this https://www.drupal.org/project/search_api_solr/issues/3280290

Schema of the module has some issue https://www.drupal.org/project/search_api_solr/issues/3280290#comment-14616330

In this add-on service can we use Solr 8.

**Comment by mkalkbrenner** [comment]
That issue on drupal.org contains a lot of outdated information.

The outdated schema happens if you don't follow the instructions and the collection gets created with Solr's built-in default config-set.

To downgrade to Solr 8, see #44
