### ISSUE TITLE
Configuration upload issue: not running in SolrCloud mode.

### ISSUE THREAD

**Issue by ilyaukin** [ddev/ddev-solr#48]
I've installed ddev-solr to my drupal10 project. Configured Search API as per readme, and try to upload configuration via:

`ddev drush search-api-solr:upload-configset --numShards=1 solr`

Got the following error:
```
In StandardSolrCloudConnector.php line 264:
                                                                          
  Configset upload failed with error code 400: Solr HTTP error: OK (400)  
  {                                                                       
    "responseHeader":{                                                    
      "status":400,                                                       
      "QTime":17},                                                        
    "error":{                                                             
      "metadata":[                                                        
        "error-class","org.apache.solr.common.SolrException",             
        "root-error-class","org.apache.solr.common.SolrException"],       
      "msg":"Solr instance is not running in SolrCloud mode.",            
      "code":400}}                                                        
```

ddev-solr version: 0.5.0
ddev version: 1.23.4

**Comment by rfay** [comment]
I didn't actually think you could get ddev-solr running in Non-solr-cloud mode.

**Comment by rfay** [comment]
I guess you didn't choose "solr cloud" when setting up your solr connection? Please do check.

![Image](https://github.com/user-attachments/assets/a8ca26b2-e7f1-4ba6-a355-e92079cd27fd)

**Comment by mkalkbrenner** [comment]
`ddev logs -s solr`

**Comment by rfay** [comment]
The README at https://git.drupalcode.org/project/search_api_solr/-/blob/4.x/README.md was helpful for me.

I just tried your drush command with my own setup (plain vanilla drupal 11, search_api_solr) and it worked OK, with solr in solr cloud mode. (The machine name of my server is `drupal_solr` and I set up search_api_solr with "Solr Cloud with Basic Auth"

`ddev drush search-api-solr:upload-configset --numShards=1 drupal_solr`

**Comment by ilyaukin** [comment]
The issue was that when I installed ddev/ddev-solr it was not getting add-on from this repo... Fixed by directly pointing to the tarball:
```
ddev get --remove solr
ddev get https://github.com/ddev/ddev-solr/archive/refs/tags/0.5.0.tar.gz
ddev restart
```

**Comment by rfay** [comment]
OK, closing. Not sure how you could get that result.
